receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Agrupar métricas antes de enviar para reduzir o uso da API.
  batch:
  # Converter o padrão das métricas geradas via spanmétrics
  metricstransform/rename_spanmetrics:
    transforms:
      - include: duration_milliseconds_sum
        action: update
        new_name: duration_sum
      - include: duration_milliseconds_count
        action: update
        new_name: duration_count
      - include: duration_milliseconds_bucket
        action: update
        new_name: duration_bucket

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      cluster: demo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

connectors:
  # basic service graph
  servicegraph:
    latency_histogram_buckets: [100ms, 250ms, 1s, 5s, 10s]
  # spanmetrics
  spanmetrics:
    # this is relevant, since grafana expects the traces_spanmetrics_ prefix
    namespace: traces.spanmetrics
    metrics_expiration: 10m
    histogram:
      unit: "s"
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.status_code
    exemplars:
      enabled: true
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
    events:
      enabled: true
      dimensions:
        - name: exception.type
        - name: exception.message
    resource_metrics_key_attributes:
      - service.name

extensions:
  # Responsável por responder a chamadas de verificação de saúde em nome do coletor.
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics, servicegraph]
      processors: [metricstransform/rename_spanmetrics, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, spanmetrics, servicegraph]
    logs:
      receivers: [otlp]
      exporters: [loki]