receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Agrupar métricas antes de enviar para reduzir o uso da API.
  batch:
  # Converter o padrão das métricas geradas via spanmétrics
  metricstransform/rename_spanmetrics:
    transforms:
      - include: duration_milliseconds_sum
        match_type: strict
        action: update
        new_name: duration_sum
      - include: duration_milliseconds_count
        match_type: strict
        action: update
        new_name: duration_count
      - include: duration_milliseconds_bucket
        match_type: strict
        action: update
        new_name: duration_bucket

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      cluster: demo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

connectors:
  spanmetrics:
    metrics_expiration: 10m
    histogram:
      explicit:
        buckets: [125ms, 500ms, 2000ms, 8000ms]
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.scheme
      - name: http.status_code
      - name: net.host.name
      - name: net.protocol.name
      - name: net.protocol.version
      - name: telemetry.sdk.language
      - name: telemetry.sdk.name
      - name: service.instance.id
      - name: host.name
    exemplars:
      enabled: false
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
    events:
      enabled: false
    resource_metrics_key_attributes:
      - service.name

extensions:
  # Responsável por responder a chamadas de verificação de saúde em nome do coletor.
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [metricstransform/rename_spanmetrics, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, spanmetrics]
    logs:
      receivers: [otlp]
      exporters: [loki]